language: node_js
node_js:
- '10'
install:
- npm ci
script:
- npm test
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key:
    secure: $NPM_API_TOKEN
  on:
    repo: technologiestiftung/flusshygiene-utils
    tags: true